monblog/routes/web.php
<?php

use App\Http\Controllers\BilletController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('billets', BilletController::class);

monblog/app/Models/Billet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Billet extends Model
{
    use HasFactory;

    public function commentaires()
    {
        return $this->hasMany(Commentaire::class);
    }
}

monblog/app/Models/Commentaire.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Commentaire extends Model
{
    use HasFactory;

    public function billet()
    {
        return $this->belongsTo(Billet::class);
    }
}

monblog/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

monblog/app/Http/Controllers/BilletController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Billet;

class BilletController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lesbillets = Billet::all();
        return view('billets', compact('lesbillets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Billet $billet)
    {
        //$lebillet = Billet::find($id);
        $lebillet = $billet;
        $lescommentaires = $lebillet->commentaires;
        //echo $lescommentaires;
        return view('billet_info', compact('lebillet', 'lescommentaires'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

monblog/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

monblog/resources/views/billet_info.blade.php
@extends('layouts.layout')

@section('correction_url')../@endsection

@section('page_contenu')
    <h2 class="titreBillet">{{$lebillet->BIL_Titre}}</h2>
    <p style="margin-top:0px;">{{$lebillet->created_at}}</p>
    <p>{{$lebillet->BIL_Contenu}}</p>

    <hr/>

    <h3>Réponses à {{$lebillet->BIL_Titre}}</h3>
    <p>
    @foreach($lescommentaires as $commentaire)
        <p>{{$commentaire->COM_Auteur}} dit :</p>
        <p>{{$commentaire->COM_Contenu}}</p>
    @endforeach
    </p>
@endsection

monblog/resources/views/billets.blade.php
@extends('layouts.layout')

@section('page_contenu')
    
    @foreach($lesbillets as $billet)
        <h1 class="titreBillet"><a href="{{route('billets.show', $billet)}}">{{$billet->BIL_Titre}}</a></h1>
        <span>{{$billet->created_at}}<br/>
        {{$billet->BIL_Contenu}}</span>
    @endforeach
    
@endsection

monblog/resources/views/layouts/layout.blade.php
<!Doctype HTML>
<html>
    <head>
        <title>Les billets du blog</title>
        <link rel="stylesheet" href="@yield('correction_url')assets/css/monblog.css" />
    </head>
    <body>
        <div id="global">
            <header id="titreBlog">
                <h1>Tous les billets :</h1>
            </header>
            @yield('page_contenu')
            <footer id="piedBlog">
                <p>Monblog - copyright 3A Info - 2022</p>
            </footer>
        </div>
    </body>
</html>